name: "Release"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  linuxRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - name: build hevm
        run: |
          nix-build -A hevmUnwrapped --out-link hevmLinux
          cp ./hevmLinux/bin/hevm ./hevm-x86_64-linux
      - name: upload linux binary
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./hevm-x86_64-linux
      - name: prepare hackage artifacts
        run: |
          nix-shell --command "cabal haddock --builddir=${{ runner.temp }}/docs --haddock-for-hackage --haddock-option=--hyperlinked-source"
          nix-shell --command "cabal sdist --builddir=${{ runner.temp }}/packages"
      - name: publish to hackage
        uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: ${{ runner.temp }}/packages
          docsPath: ${{ runner.temp }}/docs
          publish: true

